### ISSUE TITLE
Push your code! ;-)

### ISSUE THREAD

**Issue by bkanuka** [reid418/pysinope#1]
I'm about to start building a python interface to sinope thermostats. I did a github search before starting and found your repo. Even if it's rough, it would be good to see what you have and probably teamwork a bit!

**Comment by reidprojects** [comment]
No problem, I'll upload what I have until the end of the weekend. Thanks !

**Comment by reidprojects** [comment]
@bkanuka I just pushed what I have. It's still "work in progress", I'll keep working on this this week.

**Comment by bkanuka** [comment]
Haven't tried it yet, but it looks great. Thanks!
